# Generated by Django 5.1.3 on 2024-11-24 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_project_proposalutility_delete_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeocodeAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("formatted_address", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UtilityRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("utility_name", models.CharField(max_length=255)),
                ("startdate", models.DateField()),
                ("enddate", models.DateField(blank=True, null=True)),
                ("energy_rate", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "geocode_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utility_rates",
                        to="tasks.geocodeaddress",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeekdaySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=255)),
                ("values", models.JSONField()),
                (
                    "utility_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="tasks.utilityrate",
                    ),
                ),
            ],
        ),
    ]
