# Generated by Django 5.1.3 on 2024-11-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_geocodeaddress_utilityrate_weekdayschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilityrate",
            name="schedule_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="utilityrate",
            name="uri",
            field=models.URLField(blank=True, null=True),
        ),
    ]
