# Generated by Django 5.1.3 on 2024-11-24 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_remove_utilityrate_energy_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilityrate",
            name="pricing_matrix",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Tariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.CharField(max_length=255)),
                (
                    "day_period",
                    models.CharField(
                        choices=[("day", "Day"), ("night", "Night")], max_length=50
                    ),
                ),
                ("hour_start", models.IntegerField()),
                ("hour_end", models.IntegerField()),
                ("rate_per_kwh", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "utility_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to="tasks.utilityrate",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ProposalUtility",
        ),
    ]
